### ISSUE TITLE
Where should we set "compute_p=False"? 

### ISSUE THREAD

**Issue by llstela** [Zhangyanbo/INNLab#19]
If we just want INN.Conv2d output the first value, where can we set the value of "compute_p" ?

**Comment by Zhangyanbo** [comment]
Hi, Ilstela. To set `compute_p` correctly, you can use `computing_p()` method (see source code [here](https://github.com/ELIFE-ASU/INNLab/blob/main/INN/INNAbstract.py)). You should not directly set `compute_p` by let `model.compute_p=False`, because it won't set the sub-modules, while using `computing_p()` won't have this problem.
